service: bankeoFileUpload
custom: ${file(./env/${opt:origin})}
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  timeout: 120
  profile: itconbankeo
  environment:
    USERS_FILES_BUCKET: "bankeo-users-docs"
  # you can add statements to the Lambda function's IAM Role here
  apiKeys:
    - name: openKey
      value: ${self:custom.api_key}-openKey
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "qldb:*"
      Resource: "*"
functions:
  upload_user_document:
    handler: functions/users/images.upload_doc
    events:
      - http:
          path: /v1/users/upload
          method: post
          cors: true
          private: true
  create_users:
    handler: functions/users/handler.create
    events:
      - http:
          path: /v1/users/create
          method: post
          cors: true
          private: true
  validate_user_account:
    handler: functions/users/handler.validateAccount
    events:
      - http:
          path: /v1/users/validate
          method: post
          cors: true
          private: true
  apiAuthorizer:
    handler: functions/authorizer/handler.auth
