const LEDGER_NAME = "bankeoDb";
const CLIENTS_TABLE_NAME = "Client";
const BUSINESSES_TABLE_NAME = "Business";
const CLIENT_ID_INDEX_NAME = "doc_id";
const CLIENT_PHONE_NUMBER_INDEX_NAME = "phone_number";
const BUSINESS_ID_INDEX_NAME = "doc_id";
const BUSINESS_PHONE_NUMBER_INDEX_NAME = "phone_number";
const RETRY_LIMIT = 4;

module.exports = {
  LEDGER_NAME,
  CLIENTS_TABLE_NAME,
  BUSINESSES_TABLE_NAME,
  CLIENT_ID_INDEX_NAME,
  CLIENT_PHONE_NUMBER_INDEX_NAME,
  BUSINESS_ID_INDEX_NAME,
  BUSINESS_PHONE_NUMBER_INDEX_NAME,
  RETRY_LIMIT
}
